const actions = [
  'UI_EMPLOYER_REGISTER',
  'UI_EMPLOYER_SIGN_IN',
  'UI_EMPLOYER_SIGN_OUT',
  'UI_EMPLOYER_PASSWORD_CHANGE',
  'UI_EMPLOYER_USER_NAME_CHANGE',
  'UI_CONTACTS_SAVE',
  'UI_CONTACT_SELECT',
  'UI_CONTACT_ADD',
  'UI_SELECTED_CONTACT_DELETE',
  'UI_SELECTED_CONTACT_SAVE',
  'UI_SELECTED_CONTACT_CANCEL',
  'UI_SELECTED_CONTACT_FIELD_CHANGE',
  'API_CREATE_USER_SUCCESS',
  'API_CREATE_USER_ERROR',
  'API_SIGN_IN_EMPLOYER_ERROR',
  'API_READ_USERS_SUCCESS',
  'API_READ_USERS_ERROR',
  'API_UPDATE_USER_SUCCESS',
  'API_UPDATE_USER_ERROR',
  'API_DELETE_USER_SUCCESS',
  'API_DELETE_USER_ERROR'
];

const actionTypes = actions.reduce((global, key) => {
  global[key] = key; // eslint-disable-line no-param-reassign
  return global;
}, {});

export default actionTypes;
